version: 2

sources:
  - name: staging
    database: elevated-style-375519 
    schema: trip_data_all #big query dataset

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_data

models:
    - name: stg_green_tripdata
    - name: stg_yellow_tripdata
    - name: stg_fhv_tripdata